---

checks:
  cpu:
    command: "check-cpu.rb -w 90 -c 95"
    subscribers: ["ALL"]
    interval: 60
  memory_percent:
    command: "check-memory-percent.rb -w 90 -c 95"
    subscribers: ["ALL"]
    interval: 60
  swap_percent:
    command: "check-swap-percent.rb -w 30 -c 50"
    subscribers: ["ALL"]
    interval: 60
  disk_usage:
    command: "check-disk-usage.rb -w 90 -c 95"
    subscribers: ["ALL"]
    interval: 60

mailer:
  admin_gui: "https://uchiwa.private.cyberlynx.eu:3000/"
  mail_from: "sensu@cyberlynx.eu"
  mail_to: "ivan.ilves@gmail.com"
  smtp_address: "smtp"
  smtp_port: 25
  smtp_domain: "cyberlynx.eu"
