---

- name: Create Sensu client config file
  template: src=../templates/etc/sensu/conf.d/client.json.j2
            dest=/etc/sensu/conf.d/client.json
            owner=sensu
            group=sensu
            mode=0644
  notify:
    - Restart Sensu client

- name: Ensure Sensu client enabled and started
  service: name=sensu-client enabled=yes state=started

- name: Create Sensu plugins installation file
  copy: src=../files/etc/sensu/plugins.install
        dest=/etc/sensu/plugins.install
        owner=root
        group=root
        mode=0644
  notify:
    - Install Sensu plugins
