---

- name: Disable SSH server password logins
  lineinfile: dest={{ server_config_file }}
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify:
    - Restart SSH server

- name: Accept environment variables
  lineinfile: dest={{ server_config_file }}
              regexp="^AcceptEnv"
              line="AcceptEnv LANG LC_* GIT_*"
              state=present
  notify:
    - Restart SSH server
