---

- name: Import Sensu repo key
  apt_key: keyserver=p80.pool.sks-keyservers.net
           id=EB9C94BB
           state=present

- name: Add Sensu repo
  apt_repository: repo='deb https://sensu.global.ssl.fastly.net/apt sensu main'
                  state=present update_cache=yes

- name: Install Uchiwa dashboard
  apt: name=uchiwa state=latest

- name: Create Uchiwa config file
  template: src=../templates/etc/sensu/uchiwa.json.j2
            dest=/etc/sensu/uchiwa.json
            owner=uchiwa
            group=uchiwa
            mode=0640
  notify:
    - Restart Uchiwa
