#!/usr/bin/env bash
#
# Apply Ansible against selected inventory
#
. "$(dirname ${0})/_shared.sh"

if [ ${#} -lt 1 ]; then
  echo "Usage: ${0} INVENTORY [ANSIBLE_OPTIONS]"

  echo
  echo "Available inventories:"
  ls -1 ${ANSIBLE_INVENTORY_PATH}/* | sed 's|.*/|* |'
  echo

  suicide "You need to provide inventory!"
fi

INVENTORY="${1}" ; shift

ansible-playbook -b -i "${ANSIBLE_INVENTORY_PATH}/${INVENTORY}" "${ANSIBLE_PATH}/site.yml" ${@}
